### ISSUE TITLE
Set up and verify app cluster for SFVT - Statsforvalteren i Vestfold og Telemark (Test)

### ISSUE THREAD

**Issue by bengtfredh** [Altinn/altinn-platform#544] opened 2023-09-05 08:50 UTC
## Description
Set up app cluster for SFVT Test

## Infrastructure tasks [Documentation](https://pedia.altinn.cloud/altinn-3/infrastructure/environments/create-clusters/app-cluster/)
- [ ] Prepare subscription for SFVT test and production  @Herskis 
    - Rename reserved subscriptions and grant "Contributor" and "User Access Administrator" permissions to "Altinn Apps Terraform".
- [ ] Create AD-groups for SFVT @Herskis 
- [ ] Prepare pipeline for SFVT test
- [ ] Run pipeline for SFVT test
- [ ] Add dns record for SFVT cluster  @Herskis.  
- [ ] Add synthetic availibilty test https://altinnapps.grafana.net/a/grafana-synthetic-monitoring-app/checks  
          - Job Name: `<org>-<env>`
          - Target: `https://<org>.apps.<env>.altinn.no/kuberneteswrapper/api/v1/deployments`
          - Probe Location: Amsterdam
          -  Frequency - Evry - 30s
          - Validation - Regex Validation - Check fails if response body matches : `kuberneteswrapper` (invert match)
          - Advanced options - labels - `env:<env>`

## Development tasks
- [ ] Create org in Altinn Studio
- [ ] Give SFVT rights to deploy to Test on cdn
- [ ] Create and deploy app to TT02 for SFVT
- [ ] Create slack-channel for SFVT
- [ ] Notfify that cluster is ready in slack
- [x] Create scopes in Maskinporten @SandGrainOne 
- [ ] Clean up testdata.
  - [ ] Complete confirm+ hard delete instance
  - [ ] Delete app metadata from cosmos
  - [ ] Delete deployment + resources from cluster
  - [ ] Delete repository from gitea

 
## Acceptance criteria
- [ ] An application is successfully instantiated and submitted.
- [ ] Instance is successfully cleaned up: guid

**Comment by SandGrainOne** [comment] 2023-09-06 08:16
Duplicate of: https://github.com/Altinn/altinn-support-private/issues/1806

**Closed by SandGrainOne** 2023-09-06 08:16 UTC
Labels: solution/apps, area/infrastructure
